
name: Image_Caption_Generator

channels:
  - conda-forge
  - defaults
  
dependencies:
  - pip
  - pip:
    - python=3.8.0
    - tensorflow=2.4.1
    - keras=2.4.3
    - pandas=1.2.4
    - matplotlib=3.4.1
    - Pillow=8.2.0
    - scikit-learn=0.24.1
    - seaborn=0.11.1
    - tqdm=4.60.0
